# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='Product',
            new_name='product',
        ),
    ]
